js_targets = {"app.js" : [
	"src/html/unit_test.html",
	"src/html/main.html",
  "src/core/typesystem.js",
  "src/core/const.js",
  "src/util/object_cache.js",
	"tools/utils/crypto/sha1.js",
  "tools/utils/libs/lz-string/libs/base64-string-v1.1.0.js",
  "tools/utils/libs/lz-string/libs/lz-string-1.3.3.js",
  "src/core/startup_file.js",
	"src/core/webgl-debug.js",
	"src/core/webgl-utils.js",
	"src/core/J3DIMath.js",
	"src/core/J3DI.js",
	"src/util/utils.js",
  "src/util/strutils.js",
  "src/util/workerutils.js",
	"src/core/lib_api.js",
	"src/core/lib_utils.js",
	"src/util/mathlib.js",
	"src/util/parseutil.js",
	"src/util/jslzjb.js",
	"src/core/jobs.js",
	"src/ui/font_out.js",
	"src/core/ajax.js",
  "src/core/raster.js",
	"src/core/AppState.js",
	"src/core/units.js",
	"src/core/data_api.js",
	"src/core/schema.js",
	"src/core/fileapi.js",
  
  "src/mesh/mesh_types.js",
	"src/mesh/mesh.js",
  "src/mesh/mesh_api.js",
	"src/mesh/opsapi.js",
	"src/mesh/esubdivide.js",
	"src/mesh/triangulate_job.js",
  "src/mesh/triangulate_worker.js",
	"src/mesh/geodata.js",
  
	"src/mesh/triangulate.js",
	"src/mesh/subsurf.js",

	"src/view3d/events.js",
  
  "src/core/toolprops.js",
  "src/core/toolprops_iter.js",
	"src/core/toolops_api.js",

	"src/mesh/meshtools_cad.js",
	"src/mesh/meshtools_loop.js",
	"src/mesh/meshtools_create.js",

	"src/view3d/trans_ops.js",
	"src/view3d/trans_ops_special.js",
	"src/view3d/fontutils.js",
	"src/view3d/grid.js",
  "src/ui/theme.js",
	"src/view3d/draw.js",
	"src/ui/UIElement.js",
  "src/ui/UICanvas.js",
  "src/ui/UIFrame.js",
  "src/ui/UIPack.js",
	"src/ui/UIWidgets.js",
	"src/ui/UIMenu.js",
	"src/ui/RadialMenu.js",
	"src/view3d/dialog.js",
	"src/view3d/dialogs.js",
	"src/view3d/FrameManager.js",

	"src/util/dag.js",
	"src/util/dag_utils.js",
	"src/view3d/view3d.js",
	"src/view3d/view3d_ops.js",
	"src/view3d/select_ops.js",
  "src/view3d/view3d_object_ops.js",
	"src/view3d/view3d_mesh_ops.js",
	"src/object/object.js",
	"src/object/scenegraph.js",
	"src/object/scene.js",
	"src/object/object_ops.js",
	"src/core/data_api_define.js"
]}
