
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'z\x13\xacq\xe9rQTF\xb8^3Z\xa4\xee\x99'
    
_lr_action_items = {'HTML':([0,1,2,3,4,5,6,7,8,9,],[8,-7,-5,-4,8,-6,-8,-1,-9,-2,]),'CODE':([0,1,2,3,4,5,6,7,8,9,],[1,-7,-5,-4,1,-6,-8,-1,-9,-2,]),'BINDING':([0,1,2,3,4,5,6,7,8,9,],[6,-7,-5,-4,6,-6,-8,-1,-9,-2,]),'$end':([0,1,2,3,4,5,6,7,8,9,],[-3,-7,-5,-4,0,-6,-8,-1,-9,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'html':([0,4,],[2,2,]),'binding':([0,4,],[5,5,]),'statement':([0,4,],[7,9,]),'statementlist':([0,],[4,]),'code':([0,4,],[3,3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statementlist","S'",1,None,None,None),
  ('statementlist -> statement','statementlist',1,'p_statementlist','c:\\dev\\allshape\\cserver\\cs_parse.py',22),
  ('statementlist -> statementlist statement','statementlist',2,'p_statementlist','c:\\dev\\allshape\\cserver\\cs_parse.py',23),
  ('statementlist -> <empty>','statementlist',0,'p_statementlist','c:\\dev\\allshape\\cserver\\cs_parse.py',24),
  ('statement -> code','statement',1,'p_statement','c:\\dev\\allshape\\cserver\\cs_parse.py',37),
  ('statement -> html','statement',1,'p_statement','c:\\dev\\allshape\\cserver\\cs_parse.py',38),
  ('statement -> binding','statement',1,'p_statement','c:\\dev\\allshape\\cserver\\cs_parse.py',39),
  ('code -> CODE','code',1,'p_code','c:\\dev\\allshape\\cserver\\cs_parse.py',44),
  ('binding -> BINDING','binding',1,'p_binding','c:\\dev\\allshape\\cserver\\cs_parse.py',49),
  ('html -> HTML','html',1,'p_html','c:\\dev\\allshape\\cserver\\cs_parse.py',55),
]
