
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\x14}Y\xf0\x1f\x9c\xf2\x94P\xbd\x88\xfc?\xe4\xa3\xce'
    
_lr_action_items = {'HTML':([0,1,2,3,4,5,6,7,8,9,],[2,-5,-9,-7,-1,-4,-8,2,-6,-2,]),'$end':([0,1,2,3,4,5,6,7,8,9,],[-3,-5,-9,-7,-1,-4,-8,0,-6,-2,]),'CODE':([0,1,2,3,4,5,6,7,8,9,],[3,-5,-9,-7,-1,-4,-8,3,-6,-2,]),'BINDING':([0,1,2,3,4,5,6,7,8,9,],[6,-5,-9,-7,-1,-4,-8,6,-6,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'html':([0,7,],[1,1,]),'binding':([0,7,],[8,8,]),'statement':([0,7,],[4,9,]),'code':([0,7,],[5,5,]),'statementlist':([0,],[7,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statementlist","S'",1,None,None,None),
  ('statementlist -> statement','statementlist',1,'p_statementlist','c:\\dev\\allshape\\cserver\\cs_parse.py',22),
  ('statementlist -> statementlist statement','statementlist',2,'p_statementlist','c:\\dev\\allshape\\cserver\\cs_parse.py',23),
  ('statementlist -> <empty>','statementlist',0,'p_statementlist','c:\\dev\\allshape\\cserver\\cs_parse.py',24),
  ('statement -> code','statement',1,'p_statement','c:\\dev\\allshape\\cserver\\cs_parse.py',37),
  ('statement -> html','statement',1,'p_statement','c:\\dev\\allshape\\cserver\\cs_parse.py',38),
  ('statement -> binding','statement',1,'p_statement','c:\\dev\\allshape\\cserver\\cs_parse.py',39),
  ('code -> CODE','code',1,'p_code','c:\\dev\\allshape\\cserver\\cs_parse.py',44),
  ('binding -> BINDING','binding',1,'p_binding','c:\\dev\\allshape\\cserver\\cs_parse.py',49),
  ('html -> HTML','html',1,'p_html','c:\\dev\\allshape\\cserver\\cs_parse.py',60),
]
