
# parsetab_astmatch.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ast_matchCODE COMMA LBK NOT OR RBK SPECIAL STAR WORDast_match : ast_expr\n  ast_set : LBK ast_exprlist RBK\n  \n  ast_exprlist : ast_expr\n                  | ast_exprlist COMMA ast_expr\n                  |\n  ast_special : SPECIAL WORD\n  ast_expr : ast_expr CODE\n              | ast_expr ast_special\n              | ast_expr ast_set\n              | ast_expr OR ast_expr\n              | ast_expr NOT ast_expr\n              | ast_expr ast_expr STAR\n              |\n  '
    
_lr_action_items = {'CODE':([0,2,3,4,5,6,7,8,10,11,12,13,14,16,17,18,19,],[-13,4,4,-7,-8,-9,-13,-13,-13,-12,4,4,-6,4,-2,-13,4,]),'OR':([0,2,3,4,5,6,7,8,10,11,12,13,14,16,17,18,19,],[-13,7,7,-7,-8,-9,-13,-13,-13,-12,7,7,-6,7,-2,-13,7,]),'NOT':([0,2,3,4,5,6,7,8,10,11,12,13,14,16,17,18,19,],[-13,8,8,-7,-8,-9,-13,-13,-13,-12,8,8,-6,8,-2,-13,8,]),'SPECIAL':([0,2,3,4,5,6,7,8,10,11,12,13,14,16,17,18,19,],[-13,9,9,-7,-8,-9,-13,-13,-13,-12,9,9,-6,9,-2,-13,9,]),'LBK':([0,2,3,4,5,6,7,8,10,11,12,13,14,16,17,18,19,],[-13,10,10,-7,-8,-9,-13,-13,-13,-12,10,10,-6,10,-2,-13,10,]),'STAR':([0,2,3,4,5,6,7,8,10,11,12,13,14,16,17,18,19,],[-13,-13,11,-7,-8,-9,-13,-13,-13,-12,-10,-11,-6,-13,-2,-13,-13,]),'$end':([0,1,2,4,5,6,7,8,11,12,13,14,17,],[-13,0,-1,-7,-8,-9,-13,-13,-12,-10,-11,-6,-2,]),'RBK':([4,5,6,7,8,10,11,12,13,14,15,16,17,18,19,],[-7,-8,-9,-13,-13,-5,-12,-10,-11,-6,17,-3,-2,-13,-4,]),'COMMA':([4,5,6,7,8,10,11,12,13,14,15,16,17,18,19,],[-7,-8,-9,-13,-13,-5,-12,-10,-11,-6,18,-3,-2,-13,-4,]),'WORD':([9,],[14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ast_match':([0,],[1,]),'ast_expr':([0,2,3,7,8,10,12,13,16,18,19,],[2,3,3,12,13,16,3,3,3,19,3,]),'ast_special':([2,3,12,13,16,19,],[5,5,5,5,5,5,]),'ast_set':([2,3,12,13,16,19,],[6,6,6,6,6,6,]),'ast_exprlist':([10,],[15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> ast_match","S'",1,None,None,None),
  ('ast_match -> ast_expr','ast_match',1,'p_ast_match','js_ast_match.py',46),
  ('ast_set -> LBK ast_exprlist RBK','ast_set',3,'p_ast_set','js_ast_match.py',52),
  ('ast_exprlist -> ast_expr','ast_exprlist',1,'p_ast_exprlist','js_ast_match.py',60),
  ('ast_exprlist -> ast_exprlist COMMA ast_expr','ast_exprlist',3,'p_ast_exprlist','js_ast_match.py',61),
  ('ast_exprlist -> <empty>','ast_exprlist',0,'p_ast_exprlist','js_ast_match.py',62),
  ('ast_special -> SPECIAL WORD','ast_special',2,'p_ast_noderef','js_ast_match.py',76),
  ('ast_expr -> ast_expr CODE','ast_expr',2,'p_ast_expr','js_ast_match.py',82),
  ('ast_expr -> ast_expr ast_special','ast_expr',2,'p_ast_expr','js_ast_match.py',83),
  ('ast_expr -> ast_expr ast_set','ast_expr',2,'p_ast_expr','js_ast_match.py',84),
  ('ast_expr -> ast_expr OR ast_expr','ast_expr',3,'p_ast_expr','js_ast_match.py',85),
  ('ast_expr -> ast_expr NOT ast_expr','ast_expr',3,'p_ast_expr','js_ast_match.py',86),
  ('ast_expr -> ast_expr ast_expr STAR','ast_expr',3,'p_ast_expr','js_ast_match.py',87),
  ('ast_expr -> <empty>','ast_expr',0,'p_ast_expr','js_ast_match.py',88),
]
