
# parsetab_re.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BACKSLASH DIVIDE ID_PART LSBRACKET LT RSBRACKET STAR UCHARre_lit : DIVIDE re_body DIVIDE re_flagsre_body : re_first_char re_charsre_chars : re_chars re_char\n              |\n  re_first_char : re_non_term_restrict1\n                   | re_backlash_seq\n                   | re_expr_class\n  re_char : re_non_term_restrict2\n             | re_backlash_seq\n             | re_expr_class\n  re_backlash_seq : BACKSLASH re_non_termre_non_term : UCHAR\n           | LSBRACKET \n           | RSBRACKET\n           | STAR\n           | DIVIDE\n           | BACKSLASH\n           | ID_PART\n  re_non_term_restrict1 : UCHAR\n                           | RSBRACKET\n                           | ID_PART\n  re_non_term_restrict2 : UCHAR\n           | RSBRACKET\n           | STAR\n           | ID_PART\n  re_non_term_restrict3 : UCHAR\n           | LSBRACKET \n           | STAR\n           | DIVIDE\n           | ID_PART\n  re_expr_class : LSBRACKET re_class_chars RSBRACKET\n  re_class_chars : re_class_chars re_class_char\n                    |\n  re_class_char : re_non_term_restrict3\n                   | re_backlash_seq\n  re_flags : re_flags ID_PART\n              |\n  '
    
_lr_action_items = {'DIVIDE':([0,3,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,22,23,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,],[2,13,-4,-5,-6,-7,-19,-20,-21,21,-33,-2,-17,-11,-12,-13,-14,-15,-16,-18,40,-3,-8,-9,-10,-22,-23,-24,-25,-27,-31,-32,-34,-35,-26,-28,-29,-30,]),'$end':([1,13,24,42,],[0,-37,-1,-36,]),'UCHAR':([2,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,22,23,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,],[8,-4,-5,-6,-7,-19,-20,-21,17,-33,29,-17,-11,-12,-13,-14,-15,-16,-18,38,-3,-8,-9,-10,-22,-23,-24,-25,-27,-31,-32,-34,-35,-26,-28,-29,-30,]),'RSBRACKET':([2,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,22,23,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,],[9,-4,-5,-6,-7,-19,-20,-21,19,-33,30,-17,-11,-12,-13,-14,-15,-16,-18,34,-3,-8,-9,-10,-22,-23,-24,-25,-27,-31,-32,-34,-35,-26,-28,-29,-30,]),'ID_PART':([2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,],[10,-4,-5,-6,-7,-19,-20,-21,22,-33,-37,32,-17,-11,-12,-13,-14,-15,-16,-18,41,42,-3,-8,-9,-10,-22,-23,-24,-25,-27,-31,-32,-34,-35,-26,-28,-29,-30,-36,]),'BACKSLASH':([2,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,22,23,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,],[11,-4,-5,-6,-7,-19,-20,-21,15,-33,11,-17,-11,-12,-13,-14,-15,-16,-18,11,-3,-8,-9,-10,-22,-23,-24,-25,-27,-31,-32,-34,-35,-26,-28,-29,-30,]),'LSBRACKET':([2,4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,22,23,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,],[12,-4,-5,-6,-7,-19,-20,-21,18,-33,12,-17,-11,-12,-13,-14,-15,-16,-18,33,-3,-8,-9,-10,-22,-23,-24,-25,-27,-31,-32,-34,-35,-26,-28,-29,-30,]),'STAR':([4,5,6,7,8,9,10,11,12,14,15,16,17,18,19,20,21,22,23,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,],[-4,-5,-6,-7,-19,-20,-21,20,-33,31,-17,-11,-12,-13,-14,-15,-16,-18,39,-3,-8,-9,-10,-22,-23,-24,-25,-27,-31,-32,-34,-35,-26,-28,-29,-30,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'re_lit':([0,],[1,]),'re_body':([2,],[3,]),'re_first_char':([2,],[4,]),'re_non_term_restrict1':([2,],[5,]),'re_backlash_seq':([2,14,23,],[6,27,37,]),'re_expr_class':([2,14,],[7,28,]),'re_chars':([4,],[14,]),'re_non_term':([11,],[16,]),'re_class_chars':([12,],[23,]),'re_flags':([13,],[24,]),'re_char':([14,],[25,]),'re_non_term_restrict2':([14,],[26,]),'re_class_char':([23,],[35,]),'re_non_term_restrict3':([23,],[36,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> re_lit","S'",1,None,None,None),
  ('re_lit -> DIVIDE re_body DIVIDE re_flags','re_lit',4,'p_re_lit','js_regexpr_parse.py',51),
  ('re_body -> re_first_char re_chars','re_body',2,'p_re_body','js_regexpr_parse.py',56),
  ('re_chars -> re_chars re_char','re_chars',2,'p_re_chars','js_regexpr_parse.py',61),
  ('re_chars -> <empty>','re_chars',0,'p_re_chars','js_regexpr_parse.py',62),
  ('re_first_char -> re_non_term_restrict1','re_first_char',1,'p_re_first_char','js_regexpr_parse.py',71),
  ('re_first_char -> re_backlash_seq','re_first_char',1,'p_re_first_char','js_regexpr_parse.py',72),
  ('re_first_char -> re_expr_class','re_first_char',1,'p_re_first_char','js_regexpr_parse.py',73),
  ('re_char -> re_non_term_restrict2','re_char',1,'p_re_char','js_regexpr_parse.py',79),
  ('re_char -> re_backlash_seq','re_char',1,'p_re_char','js_regexpr_parse.py',80),
  ('re_char -> re_expr_class','re_char',1,'p_re_char','js_regexpr_parse.py',81),
  ('re_backlash_seq -> BACKSLASH re_non_term','re_backlash_seq',2,'p_re_backlash_seq','js_regexpr_parse.py',87),
  ('re_non_term -> UCHAR','re_non_term',1,'p_re_non_term','js_regexpr_parse.py',92),
  ('re_non_term -> LSBRACKET','re_non_term',1,'p_re_non_term','js_regexpr_parse.py',93),
  ('re_non_term -> RSBRACKET','re_non_term',1,'p_re_non_term','js_regexpr_parse.py',94),
  ('re_non_term -> STAR','re_non_term',1,'p_re_non_term','js_regexpr_parse.py',95),
  ('re_non_term -> DIVIDE','re_non_term',1,'p_re_non_term','js_regexpr_parse.py',96),
  ('re_non_term -> BACKSLASH','re_non_term',1,'p_re_non_term','js_regexpr_parse.py',97),
  ('re_non_term -> ID_PART','re_non_term',1,'p_re_non_term','js_regexpr_parse.py',98),
  ('re_non_term_restrict1 -> UCHAR','re_non_term_restrict1',1,'p_re_non_term_restrict1','js_regexpr_parse.py',103),
  ('re_non_term_restrict1 -> RSBRACKET','re_non_term_restrict1',1,'p_re_non_term_restrict1','js_regexpr_parse.py',104),
  ('re_non_term_restrict1 -> ID_PART','re_non_term_restrict1',1,'p_re_non_term_restrict1','js_regexpr_parse.py',105),
  ('re_non_term_restrict2 -> UCHAR','re_non_term_restrict2',1,'p_re_non_term_restrict2','js_regexpr_parse.py',110),
  ('re_non_term_restrict2 -> RSBRACKET','re_non_term_restrict2',1,'p_re_non_term_restrict2','js_regexpr_parse.py',111),
  ('re_non_term_restrict2 -> STAR','re_non_term_restrict2',1,'p_re_non_term_restrict2','js_regexpr_parse.py',112),
  ('re_non_term_restrict2 -> ID_PART','re_non_term_restrict2',1,'p_re_non_term_restrict2','js_regexpr_parse.py',113),
  ('re_non_term_restrict3 -> UCHAR','re_non_term_restrict3',1,'p_re_non_term_restrict3','js_regexpr_parse.py',119),
  ('re_non_term_restrict3 -> LSBRACKET','re_non_term_restrict3',1,'p_re_non_term_restrict3','js_regexpr_parse.py',120),
  ('re_non_term_restrict3 -> STAR','re_non_term_restrict3',1,'p_re_non_term_restrict3','js_regexpr_parse.py',121),
  ('re_non_term_restrict3 -> DIVIDE','re_non_term_restrict3',1,'p_re_non_term_restrict3','js_regexpr_parse.py',122),
  ('re_non_term_restrict3 -> ID_PART','re_non_term_restrict3',1,'p_re_non_term_restrict3','js_regexpr_parse.py',123),
  ('re_expr_class -> LSBRACKET re_class_chars RSBRACKET','re_expr_class',3,'p_re_expr_class','js_regexpr_parse.py',128),
  ('re_class_chars -> re_class_chars re_class_char','re_class_chars',2,'p_re_class_chars','js_regexpr_parse.py',134),
  ('re_class_chars -> <empty>','re_class_chars',0,'p_re_class_chars','js_regexpr_parse.py',135),
  ('re_class_char -> re_non_term_restrict3','re_class_char',1,'p_re_class_char','js_regexpr_parse.py',144),
  ('re_class_char -> re_backlash_seq','re_class_char',1,'p_re_class_char','js_regexpr_parse.py',145),
  ('re_flags -> re_flags ID_PART','re_flags',2,'p_re_flags','js_regexpr_parse.py',151),
  ('re_flags -> <empty>','re_flags',0,'p_re_flags','js_regexpr_parse.py',152),
]
